print('----------------- Menu de Automacao de Atividades -----------------')
print('')
print('1) Verificar as datas no MONITOR DE CARGA')
print('2) Verificar a data do Demonstrativo do Gross')
print('3) Executar processo da Nova Fibra')
print('4) Copiar e tratar o Demonstrativo de Gross')
print('')
x =  input(('Selecione uma das opcoes acima: #'))
print(x)